--INSERT 1--
INSERT INTO ingresos.xxfr_cabecera_factura(
IDFACTURAPRIMAVERA,
facilityNumber,
companyAccountCode,
businessUnitName,
transactionSource,
transactionType,
creationDateTRX,
creationDateGL,
currency,
billToConsumerName,
billToLocation,
paymentTermDays,
paymentTermDate,
gracePeriod,
paymentMethod,
DFFheaderContext,
contractNumber,
contextRentas,
localNumber,
addendum,
tipoCobranza,
divisionType,
projectId,
generationType,
groupType,
bankName,
bankAccountNumber,
totalAmount,
idbatch
) VALUES (
11111,
'E12345',
174,
'LMF MUNDO E - RENTAS',
'RENTA',
'FAC_INGRESOS_MN',
TO_DATE('01/10/2018'),
TO_DATE('01/10/2018'),
'MXN',
'Nueva Wal-Mart DE MEXICO SA DE CV',
'160501',
'15',
'15 days',
'1',
'3',
'RENTAS',
'194',
'RENTAS',
'A201',
'G03',
'LINEA CAPTURA',
'ARRENDAMIENTO',
'8977',
'ONLY_CAPTURE_LINE',
'RENT_ACCESORIES',
'BBVA Bancomer, S.A.',
'111629107',
'1300',
'11111'
);
--INSERT 2--
INSERT INTO ingresos.xxfr_cabecera_factura(
IDFACTURAPRIMAVERA,
facilityNumber,
companyAccountCode,
businessUnitName,
transactionSource,
transactionType,
creationDateTRX,
creationDateGL,
currency,
billToConsumerName,
billToLocation,
paymentTermDays,
paymentTermDate,
gracePeriod,
paymentMethod,
DFFheaderContext,
contractNumber,
contextRentas,
localNumber,
addendum,
tipoCobranza,
divisionType,
projectId,
generationType,
groupType,
bankName,
bankAccountNumber,
totalAmount,
idbatch
) VALUES (
11112,
'E12345',
174,
'LMF MUNDO E - RENTAS',
'RENTA',
'FAC_INGRESOS_MN',
TO_DATE('01/09/2018'),
TO_DATE('01/09/2018'),
'MXN',
'Nueva Wal-Mart DE MEXICO SA DE CV',
'160501',
'15',
'15 days',
'1',
'3',
'RENTAS',
'194',
'RENTAS',
'A201',
'G03',
'LINEA CAPTURA',
'ARRENDAMIENTO',
'8977',
'ONLY_CAPTURE_LINE',
'RENT_ACCESORIES',
'BBVA Bancomer, S.A.',
'111629107',
'1300',
'11111'
);
--INSERT 3--
INSERT INTO ingresos.xxfr_cabecera_factura(
IDFACTURAPRIMAVERA,
facilityNumber,
companyAccountCode,
businessUnitName,
transactionSource,
transactionType,
creationDateTRX,
creationDateGL,
currency,
billToConsumerName,
billToLocation,
paymentTermDays,
paymentTermDate,
gracePeriod,
paymentMethod,
DFFheaderContext,
contractNumber,
contextRentas,
localNumber,
addendum,
tipoCobranza,
divisionType,
projectId,
generationType,
groupType,
bankName,
bankAccountNumber,
totalAmount,
idbatch
) VALUES (
11113,
'E12345',
174,
'LMF MUNDO E - RENTAS',
'RENTA',
'FAC_INGRESOS_MN',
TO_DATE('01/09/2018'),
TO_DATE('01/09/2018'),
'MXN',
'Nueva Wal-Mart DE MEXICO SA DE CV',
'160501',
'15',
'15 days',
'1',
'3',
'RENTAS',
'195',
'RENTAS',
'A201',
'G03',
'LINEA CAPTURA',
'ARRENDAMIENTO',
'8977',
'ONLY_CAPTURE_LINE',
'RENT_ACCESORIES',
'BBVA Bancomer, S.A.',
'111629107',
'1300',
'11111'
);
--INSERT 4--
INSERT INTO ingresos.xxfr_cabecera_factura(
IDFACTURAPRIMAVERA,
facilityNumber,
companyAccountCode,
businessUnitName,
transactionSource,
transactionType,
creationDateTRX,
creationDateGL,
currency,
billToConsumerName,
billToLocation,
paymentTermDays,
paymentTermDate,
gracePeriod,
paymentMethod,
DFFheaderContext,
contractNumber,
contextRentas,
localNumber,
addendum,
tipoCobranza,
divisionType,
projectId,
generationType,
groupType,
bankName,
bankAccountNumber,
totalAmount,
idbatch
) VALUES (
11114,
'E12345',
174,
'LMF MUNDO E - RENTAS',
'RENTA',
'FAC_INGRESOS_MN',
TO_DATE('01/09/2018'),
TO_DATE('01/09/2018'),
'MXN',
'Nueva Wal-Mart DE MEXICO SA DE CV',
'160501',
'15',
'15 days',
'1',
'3',
'RENTAS',
'195',
'RENTAS',
'A201',
'G03',
'REFERENCIA',
'ARRENDAMIENTO',
'8977',
'ONLY_CAPTURE_LINE',
'RENT_ACCESORIES',
'BBVA Bancomer, S.A.',
'111629107',
'1300',
'11111'
);
--INSERT 5--
INSERT INTO ingresos.xxfr_cabecera_factura(
IDFACTURAPRIMAVERA,
facilityNumber,
companyAccountCode,
businessUnitName,
transactionSource,
transactionType,
creationDateTRX,
creationDateGL,
currency,
billToConsumerName,
billToLocation,
paymentTermDays,
paymentTermDate,
gracePeriod,
paymentMethod,
DFFheaderContext,
contractNumber,
contextRentas,
localNumber,
addendum,
tipoCobranza,
divisionType,
projectId,
generationType,
groupType,
bankName,
bankAccountNumber,
totalAmount,
idbatch
) VALUES (
11115,
'E12345',
174,
'LMF MUNDO E - RENTAS',
'RENTA',
'FAC_INGRESOS_MN',
TO_DATE('01/10/2018'),
TO_DATE('01/10/2018'),
'MXN',
'Nueva Wal-Mart DE MEXICO SA DE CV',
'160501',
'15',
'15 days',
'1',
'3',
'RENTAS',
'194',
'RENTAS',
'A201',
'G03',
'LINEA CAPTURA',
'ARRENDAMIENTO',
'8977',
'ONLY_CAPTURE_LINE',
'RENTA_BASE',
'BBVA Bancomer, S.A.',
'111629107',
'1300',
'11111'
);
--INSERT LC 1--
INSERT INTO xxfr_linea_captura (
lineacapturaref,
sistemaorigen,
lineacaptura,
referencia,
fechacreacion,
fechavigencia,
montolineacaptura,
estatuslc,
banco,
cuentabancaria,
entidadlegal,
unidadnegocio,
division,
centrocostosproyecto,
numerorecibo,
tipocobranza
) VALUES(
'012381234567899999999911811218',
'Primavera',
'012381234567899999999911811218',
'123',
TO_DATE('07/11/18'),
TO_DATE('21/11/18'),
1000.00,
'CREADA',
'BBVA Bancomer, S.A.',
'111629107',
'AAA',
'LMF MUNDO E - RENTAS',
'ARRENDAMIENTO',
'E12345',
'111',
'LINEA CAPTURA'
)
--DETALLE FACTURA 1--
INSERT INTO
xxfr_invoice_lines( 
idfacturaprimavera, 
linenumber, 
description_origen, 
descriptionmanual, 
memolinename, 
quantity, 
taxclassificationcode, 
taxrate, 
clasificadordescuento, 
descadicional1, 
descadicional2, 
descadicional3, 
descadicional4, 
descadicional5, 
montobrutolinea, 
montonetolinea, 
idconcepto, 
fechadesde, 
fechahasta, 
fechaexigibilidad
)
VALUES (
11111,
1,
'RENTA DEPARTAMENTO',
'RENTA ,ÍNIM DEPARTAMENTA CLASE A ZONA 1',
'InvoiceReceivableMappingBP',
1,
12,
'16%',
'00',
'DESCADICIONAL1',
'DESCADICIONAL2',
'DESCADICIONAL3',
'DESCADICIONAL4',
'DESCADICIONAL5',
5000.00,
5800.00,
123,
TO_DATE('01/10/2018'),
TO_DATE('31/10/2018'),
TO_DATE('05/11/2018')
);
--DETALLE FACTURA 2--
INSERT INTO
xxfr_invoice_lines( 
idfacturaprimavera, 
linenumber, 
description_origen, 
descriptionmanual, 
memolinename, 
quantity, 
taxclassificationcode, 
taxrate, 
clasificadordescuento, 
descadicional1, 
descadicional2, 
descadicional3, 
descadicional4, 
descadicional5, 
montobrutolinea, 
montonetolinea, 
idconcepto, 
fechadesde, 
fechahasta, 
fechaexigibilidad
)
VALUES (
11111,
2,
'ACCESORIOS DEPARTAMENTO',
'ACCESORIOS BÁSICOS, DEPARTAMENTO CLASE A ZONA 1',
'InvoiceReceivableMappingBP',
1,
12,
'16%',
'00',
'DESCADICIONAL1',
'DESCADICIONAL2',
'DESCADICIONAL3',
'DESCADICIONAL4',
'DESCADICIONAL5',
2000.00,
2320.00,
123,
TO_DATE('01/10/2018'),
TO_DATE('31/10/2018'),
TO_DATE('05/11/2018')
);