<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.negocio.tic.frisa.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ws.negocio.tic.frisa.mx/" name="GestorFacturasWS">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://ws.negocio.tic.frisa.mx/" schemaLocation="GestorFacturasWS1.xsd"/>
    </xsd:schema>
  </types>
  <message name="consultarLCFacturas">
    <part name="parameters" element="tns:consultarLCFacturas"/>
  </message>
  <message name="consultarLCFacturasResponse">
    <part name="parameters" element="tns:consultarLCFacturasResponse"/>
  </message>
  <message name="consultaDetalleFacturas">
    <part name="parameters" element="tns:consultaDetalleFacturas"/>
  </message>
  <message name="consultaDetalleFacturasResponse">
    <part name="parameters" element="tns:consultaDetalleFacturasResponse"/>
  </message>
  <portType name="GestorFacturasWS">
    <operation name="consultarLCFacturas">
      <input wsam:Action="http://ws.negocio.tic.frisa.mx/GestorFacturasWS/consultarLCFacturasRequest" message="tns:consultarLCFacturas"/>
      <output wsam:Action="http://ws.negocio.tic.frisa.mx/GestorFacturasWS/consultarLCFacturasResponse" message="tns:consultarLCFacturasResponse"/>
    </operation>
    <operation name="consultaDetalleFacturas">
      <input wsam:Action="http://ws.negocio.tic.frisa.mx/GestorFacturasWS/consultaDetalleFacturasRequest" message="tns:consultaDetalleFacturas"/>
      <output wsam:Action="http://ws.negocio.tic.frisa.mx/GestorFacturasWS/consultaDetalleFacturasResponse" message="tns:consultaDetalleFacturasResponse"/>
    </operation>
  </portType>
  <binding name="GestorFacturasWSPortBinding" type="tns:GestorFacturasWS">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="consultarLCFacturas">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="consultaDetalleFacturas">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="GestorFacturasWS">
    <port name="GestorFacturasWSPort" binding="tns:GestorFacturasWSPortBinding">
      <soap:address location="https://129.191.25.150:7002/frisa-servicios/GestorFacturasWS"/>
    </port>
  </service>
</definitions>