package mx.frisa.tic.negocio.ws;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class CatalogoWSPortClient {
    public static void main(String[] args) {
        CatalogoWS_Service catalogoWS_Service = new CatalogoWS_Service();
        CatalogoWS catalogoWS = catalogoWS_Service.getCatalogoWSPort();
        // Add your code to call the desired methods.


    }
}
