
package mx.frisa.tic.negocio.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "CatalogoWS", targetNamespace = "http://ws.negocio.tic.frisa.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface CatalogoWS {


    /**
     *
     * @param clave
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarPais", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarPais")
    @ResponseWrapper(localName = "consultarPaisResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarPaisResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarPaisRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarPaisResponse")
    public String consultarPais(@WebParam(name = "id", targetNamespace = "") int id,
                                @WebParam(name = "clave", targetNamespace = "") String clave);

    /**
     *
     * @return
     *     returns java.util.List<mx.frisa.tic.negocio.ws.TipoMonedaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTipoMoneda", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarTipoMoneda")
    @ResponseWrapper(localName = "consultarTipoMonedaResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarTipoMonedaResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarTipoMonedaRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarTipoMonedaResponse")
    public List<TipoMonedaDTO> consultarTipoMoneda();

    /**
     *
     * @param numeroCuenta
     * @return
     *     returns java.util.List<mx.frisa.tic.negocio.ws.CuentaBancariaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCuentaBancaria", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarCuentaBancaria")
    @ResponseWrapper(localName = "consultarCuentaBancariaResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarCuentaBancariaResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarCuentaBancariaRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarCuentaBancariaResponse")
    public List<CuentaBancariaDTO> consultarCuentaBancaria(@WebParam(name = "numeroCuenta", targetNamespace = "")
                                                           String numeroCuenta);

    /**
     *
     * @return
     * returns mx.frisa.tic.negocio.ws.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCuentasBancarias", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ActualizarCuentasBancarias")
    @ResponseWrapper(localName = "actualizarCuentasBancariasResponse",
                     targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ActualizarCuentasBancariasResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/actualizarCuentasBancariasRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/actualizarCuentasBancariasResponse")
    public RespuestaDTO actualizarCuentasBancarias();

    /**
     *
     * @return
     * returns mx.frisa.tic.negocio.ws.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarUsuarios", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ActualizarUsuarios")
    @ResponseWrapper(localName = "actualizarUsuariosResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ActualizarUsuariosResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/actualizarUsuariosRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/actualizarUsuariosResponse")
    public RespuestaDTO actualizarUsuarios();

    /**
     *
     * @param centroCostos
     * @return
     * returns java.util.List<mx.frisa.tic.negocio.ws.ConsultarCentroCostosDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCentroCostos", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarCentroCostos")
    @ResponseWrapper(localName = "consultarCentroCostosResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarCentroCostosResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarCentroCostosRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarCentroCostosResponse")
    public List<ConsultarCentroCostosDTO> consultarCentroCostos(@WebParam(name = "centroCostos", targetNamespace = "")
                                                                String centroCostos);

    /**
     *
     * @param unidadNegocio
     * @return
     * returns java.util.List<mx.frisa.tic.negocio.ws.ConsultarUniNegocioDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarUnidadNegocio", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarUnidadNegocio")
    @ResponseWrapper(localName = "consultarUnidadNegocioResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarUnidadNegocioResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarUnidadNegocioRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarUnidadNegocioResponse")
    public List<ConsultarUniNegocioDTO> consultarUnidadNegocio(@WebParam(name = "unidadNegocio", targetNamespace = "")
                                                               String unidadNegocio);

    /**
     *
     * @param usuario
     * @return
     * returns java.util.List<mx.frisa.tic.negocio.ws.ConsultarUsuarioDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarUsuarios", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarUsuarios")
    @ResponseWrapper(localName = "consultarUsuariosResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarUsuariosResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarUsuariosRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/consultarUsuariosResponse")
    public List<ConsultarUsuarioDTO> consultarUsuarios(@WebParam(name = "usuario", targetNamespace = "")
                                                       String usuario);

    /**
     *
     * @return
     * returns mx.frisa.tic.negocio.ws.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarCentroCosto", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ActualizarCentroCosto")
    @ResponseWrapper(localName = "actualizarCentroCostoResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ActualizarCentroCostoResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/CatalogoWS/actualizarCentroCostoRequest",
            output = "http://ws.negocio.tic.frisa.mx/CatalogoWS/actualizarCentroCostoResponse")
    public RespuestaDTO actualizarCentroCosto();

}
