
package mx.frisa.tic.negocio.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CatalogoWS", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                  wsdlLocation =
                  "https://129.191.25.150:7002/frisa-servicios/CatalogoWS?WSDL#%7Bhttp%3A%2F%2Fws.negocio.tic.frisa.mx%2F%7DCatalogoWS")
public class CatalogoWS_Service extends Service {

    private final static URL CATALOGOWS_WSDL_LOCATION;
    private final static WebServiceException CATALOGOWS_EXCEPTION;
    private final static QName CATALOGOWS_QNAME = new QName("http://ws.negocio.tic.frisa.mx/", "CatalogoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://192.168.80.1:7001/frisa-servicios/CatalogoWS?WSDL#%7Bhttp%3A%2F%2Fws.negocio.tic.frisa.mx%2F%7DCatalogoWS");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATALOGOWS_WSDL_LOCATION = url;
        CATALOGOWS_EXCEPTION = e;
    }

    public CatalogoWS_Service() {
        super(__getWsdlLocation(), CATALOGOWS_QNAME);
    }

    public CatalogoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATALOGOWS_QNAME, features);
    }

    public CatalogoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CATALOGOWS_QNAME);
    }

    public CatalogoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATALOGOWS_QNAME, features);
    }

    public CatalogoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CatalogoWS
     */
    @WebEndpoint(name = "CatalogoWSPort")
    public CatalogoWS getCatalogoWSPort() {
        return super.getPort(new QName("http://ws.negocio.tic.frisa.mx/", "CatalogoWSPort"), CatalogoWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatalogoWS
     */
    @WebEndpoint(name = "CatalogoWSPort")
    public CatalogoWS getCatalogoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.negocio.tic.frisa.mx/", "CatalogoWSPort"), CatalogoWS.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CATALOGOWS_EXCEPTION != null) {
            throw CATALOGOWS_EXCEPTION;
        }
        return CATALOGOWS_WSDL_LOCATION;
    }

}
