
package mx.frisa.tic.negocio.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "GestorLineaCapturaWS", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                  wsdlLocation =
                  "https://129.191.25.150:7002/frisa-servicios/GestorLineaCapturaWS?WSDL#%7Bhttp%3A%2F%2Fws.negocio.tic.frisa.mx%2F%7DGestorLineaCapturaWS")
public class GestorLineaCapturaWS_Service extends Service {

    private final static URL GESTORLINEACAPTURAWS_WSDL_LOCATION;
    private final static WebServiceException GESTORLINEACAPTURAWS_EXCEPTION;
    private final static QName GESTORLINEACAPTURAWS_QNAME =
        new QName("http://ws.negocio.tic.frisa.mx/", "GestorLineaCapturaWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://129.191.25.150:7002/frisa-servicios/GestorLineaCapturaWS?WSDL#%7Bhttp%3A%2F%2Fws.negocio.tic.frisa.mx%2F%7DGestorLineaCapturaWS");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTORLINEACAPTURAWS_WSDL_LOCATION = url;
        GESTORLINEACAPTURAWS_EXCEPTION = e;
    }

    public GestorLineaCapturaWS_Service() {
        super(__getWsdlLocation(), GESTORLINEACAPTURAWS_QNAME);
    }

    public GestorLineaCapturaWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTORLINEACAPTURAWS_QNAME, features);
    }

    public GestorLineaCapturaWS_Service(URL wsdlLocation) {
        super(wsdlLocation, GESTORLINEACAPTURAWS_QNAME);
    }

    public GestorLineaCapturaWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTORLINEACAPTURAWS_QNAME, features);
    }

    public GestorLineaCapturaWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestorLineaCapturaWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GestorLineaCapturaWS
     */
    @WebEndpoint(name = "GestorLineaCapturaWSPort")
    public GestorLineaCapturaWS getGestorLineaCapturaWSPort() {
        return super.getPort(new QName("http://ws.negocio.tic.frisa.mx/", "GestorLineaCapturaWSPort"),
                             GestorLineaCapturaWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestorLineaCapturaWS
     */
    @WebEndpoint(name = "GestorLineaCapturaWSPort")
    public GestorLineaCapturaWS getGestorLineaCapturaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.negocio.tic.frisa.mx/", "GestorLineaCapturaWSPort"),
                             GestorLineaCapturaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTORLINEACAPTURAWS_EXCEPTION != null) {
            throw GESTORLINEACAPTURAWS_EXCEPTION;
        }
        return GESTORLINEACAPTURAWS_WSDL_LOCATION;
    }

}
