
package mx.frisa.tic.negocio.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "GestorPagosWS", targetNamespace = "http://ws.negocio.tic.frisa.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface GestorPagosWS {


    /**
     *
     * @param filtros
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaPagoSinReferencia
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarPagosSinReferencia", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarPagosSinReferencia")
    @ResponseWrapper(localName = "consultarPagosSinReferenciaResponse",
                     targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarPagosSinReferenciaResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/consultarPagosSinReferenciaRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/consultarPagosSinReferenciaResponse")
    public RespuestaPagoSinReferencia consultarPagosSinReferencia(@WebParam(name = "filtros", targetNamespace = "")
                                                                  FiltroPagoSinReferencia filtros);

    /**
     *
     * @param filtros
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaClienteDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarReferenciaLCExistente", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarReferenciaLCExistente")
    @ResponseWrapper(localName = "consultarReferenciaLCExistenteResponse",
                     targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarReferenciaLCExistenteResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/consultarReferenciaLCExistenteRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/consultarReferenciaLCExistenteResponse")
    public RespuestaClienteDTO consultarReferenciaLCExistente(@WebParam(name = "filtros", targetNamespace = "")
                                                              PeticionExistente filtros);

    /**
     *
     * @param aplicarPago
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "aplicarPagoManual", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.AplicarPagoManual")
    @ResponseWrapper(localName = "aplicarPagoManualResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.AplicarPagoManualResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/aplicarPagoManualRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/aplicarPagoManualResponse")
    public RespuestaDTO aplicarPagoManual(@WebParam(name = "aplicarPago", targetNamespace = "")
                                          AplicarPagoDTO aplicarPago);

    /**
     *
     * @param pago
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaProcesaFacturasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarPago", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.GenerarPago")
    @ResponseWrapper(localName = "generarPagoResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.GenerarPagoResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/generarPagoRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorPagosWS/generarPagoResponse")
    public RespuestaProcesaFacturasDTO generarPago(@WebParam(name = "pago", targetNamespace = "") List<PagoDTO> pago);

}
