
package mx.frisa.tic.negocio.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "GestorLineaCapturaWS", targetNamespace = "http://ws.negocio.tic.frisa.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface GestorLineaCapturaWS {


    /**
     *
     * @param lineaCaptura
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaLineaCapturaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarLineaCaptura", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarLineaCaptura")
    @ResponseWrapper(localName = "consultarLineaCapturaResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarLineaCapturaResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultarLineaCapturaRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultarLineaCapturaResponse")
    public RespuestaLineaCapturaDTO consultarLineaCaptura(@WebParam(name = "lineaCaptura", targetNamespace = "")
                                                          LineaCapturaDTO lineaCaptura);

    /**
     *
     * @param idBatch
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ejecutaBatchLC", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.EjecutaBatchLC")
    @ResponseWrapper(localName = "ejecutaBatchLCResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.EjecutaBatchLCResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/ejecutaBatchLCRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/ejecutaBatchLCResponse")
    public int ejecutaBatchLC(@WebParam(name = "idBatch", targetNamespace = "") String idBatch);

    /**
     *
     * @param idBatch
     * @return
     *     returns java.util.List<mx.frisa.tic.negocio.ws.LineaCaptutaFacturaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaLCGeneradas", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultaLCGeneradas")
    @ResponseWrapper(localName = "consultaLCGeneradasResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultaLCGeneradasResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaLCGeneradasRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaLCGeneradasResponse")
    public List<LineaCaptutaFacturaDTO> consultaLCGeneradas(@WebParam(name = "idBatch", targetNamespace = "")
                                                            String idBatch);

    /**
     *
     * @param arg0
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarIdERP", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ActualizarIdERP")
    @ResponseWrapper(localName = "actualizarIdERPResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ActualizarIdERPResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/actualizarIdERPRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/actualizarIdERPResponse")
    public RespuestaDTO actualizarIdERP(@WebParam(name = "arg0", targetNamespace = "")
                                        List<FacturaActualizaIdERPDTO> arg0);

    /**
     *
     * @param facturas
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaCargaFacturaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargarFactura", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.CargarFactura")
    @ResponseWrapper(localName = "cargarFacturaResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.CargarFacturaResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/cargarFacturaRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/cargarFacturaResponse")
    public RespuestaCargaFacturaDTO cargarFactura(@WebParam(name = "facturas", targetNamespace = "")
                                                  PeticionCargaFacturaDTO facturas);

    /**
     *
     * @param uuid
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaCargaFacturaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEstadoCarga", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarEstadoCarga")
    @ResponseWrapper(localName = "consultarEstadoCargaResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarEstadoCargaResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultarEstadoCargaRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultarEstadoCargaResponse")
    public RespuestaCargaFacturaDTO consultarEstadoCarga(@WebParam(name = "uuid", targetNamespace = "") String uuid);

    /**
     *
     * @param idBatch
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaBatchFinalizado", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultaBatchFinalizado")
    @ResponseWrapper(localName = "consultaBatchFinalizadoResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultaBatchFinalizadoResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaBatchFinalizadoRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaBatchFinalizadoResponse")
    public String consultaBatchFinalizado(@WebParam(name = "idBatch", targetNamespace = "") String idBatch);

    /**
     *
     * @param lineaCaptura
     * @param unidadNegocio
     * @param entidadLegal
     * @param banco
     * @param referencia
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaDetalleLineaCapturaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDetalleLineaCaptura", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultaDetalleLineaCaptura")
    @ResponseWrapper(localName = "consultaDetalleLineaCapturaResponse",
                     targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultaDetalleLineaCapturaResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaDetalleLineaCapturaRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaDetalleLineaCapturaResponse")
    public RespuestaDetalleLineaCapturaDTO consultaDetalleLineaCaptura(@WebParam(name = "lineaCaptura",
                                                                                 targetNamespace = "")
                                                                       String lineaCaptura,
                                                                       @WebParam(name = "entidadLegal",
                                                                                 targetNamespace = "")
                                                                       String entidadLegal,
                                                                       @WebParam(name = "referencia",
                                                                                 targetNamespace = "")
                                                                       String referencia,
                                                                       @WebParam(name = "banco", targetNamespace = "")
                                                                       String banco,
                                                                       @WebParam(name = "unidadNegocio",
                                                                                 targetNamespace = "")
                                                                       String unidadNegocio);

    /**
     *
     * @param facturaERP
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaDetalleLCPagosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDetalleLCPagos", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultaDetalleLCPagos")
    @ResponseWrapper(localName = "consultaDetalleLCPagosResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultaDetalleLCPagosResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaDetalleLCPagosRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaDetalleLCPagosResponse")
    public RespuestaDetalleLCPagosDTO consultaDetalleLCPagos(@WebParam(name = "facturaERP", targetNamespace = "")
                                                             String facturaERP);

    /**
     *
     * @param cliente
     * @param unidadNegocio
     * @param cuenta
     * @param centroCostos
     * @param entidadLegal
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaLCFactDetDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaLCFactDet", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultaLCFactDet")
    @ResponseWrapper(localName = "consultaLCFactDetResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultaLCFactDetResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaLCFactDetRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaLCFactDetResponse")
    public RespuestaLCFactDetDTO consultaLCFactDet(@WebParam(name = "cliente", targetNamespace = "") String cliente,
                                                   @WebParam(name = "cuenta", targetNamespace = "") String cuenta,
                                                   @WebParam(name = "centroCostos", targetNamespace = "")
                                                   String centroCostos,
                                                   @WebParam(name = "entidadLegal", targetNamespace = "")
                                                   String entidadLegal,
                                                   @WebParam(name = "unidadNegocio", targetNamespace = "")
                                                   String unidadNegocio);

    /**
     *
     * @param lineaCaptura
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaNumeroFacturas", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultaNumeroFacturas")
    @ResponseWrapper(localName = "consultaNumeroFacturasResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultaNumeroFacturasResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaNumeroFacturasRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorLineaCapturaWS/consultaNumeroFacturasResponse")
    public int consultaNumeroFacturas(@WebParam(name = "lineaCaptura", targetNamespace = "") String lineaCaptura);

}
