package mx.frisa.tic.negocio.ws;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class GestorLineaCapturaWSPortClient {
    public static void main(String[] args) {
        GestorLineaCapturaWS_Service gestorLineaCapturaWS_Service = new GestorLineaCapturaWS_Service();
        GestorLineaCapturaWS gestorLineaCapturaWS = gestorLineaCapturaWS_Service.getGestorLineaCapturaWSPort();
        // Add your code to call the desired methods.


    }
}
