<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://ws.negocio.tic.frisa.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://ws.negocio.tic.frisa.mx/" name="GestorAccesoWS">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://ws.negocio.tic.frisa.mx/" schemaLocation="GestorAccesoWS1.xsd"/>
    </xsd:schema>
  </types>
  <message name="agregarUsuario">
    <part name="parameters" element="tns:agregarUsuario"/>
  </message>
  <message name="agregarUsuarioResponse">
    <part name="parameters" element="tns:agregarUsuarioResponse"/>
  </message>
  <message name="consultarAccesos">
    <part name="parameters" element="tns:consultarAccesos"/>
  </message>
  <message name="consultarAccesosResponse">
    <part name="parameters" element="tns:consultarAccesosResponse"/>
  </message>
  <portType name="GestorAccesoWS">
    <operation name="agregarUsuario">
      <input wsam:Action="http://ws.negocio.tic.frisa.mx/GestorAccesoWS/agregarUsuarioRequest" message="tns:agregarUsuario"/>
      <output wsam:Action="http://ws.negocio.tic.frisa.mx/GestorAccesoWS/agregarUsuarioResponse" message="tns:agregarUsuarioResponse"/>
    </operation>
    <operation name="consultarAccesos">
      <input wsam:Action="http://ws.negocio.tic.frisa.mx/GestorAccesoWS/consultarAccesosRequest" message="tns:consultarAccesos"/>
      <output wsam:Action="http://ws.negocio.tic.frisa.mx/GestorAccesoWS/consultarAccesosResponse" message="tns:consultarAccesosResponse"/>
    </operation>
  </portType>
  <binding name="GestorAccesoWSPortBinding" type="tns:GestorAccesoWS">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="agregarUsuario">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="consultarAccesos">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="GestorAccesoWS">
    <port name="GestorAccesoWSPort" binding="tns:GestorAccesoWSPortBinding">
      <soap:address location="http://192.168.80.1:7001/frisa-servicios/GestorAccesoWS"/>
    </port>
  </service>
</definitions>