
package mx.frisa.tic.negocio.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "GestorAccesoWS", targetNamespace = "http://ws.negocio.tic.frisa.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface GestorAccesoWS {


    /**
     *
     * @param usuarioAcceso
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarUsuario", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.ConsultarUsuario")
    @ResponseWrapper(localName = "consultarUsuarioResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.ConsultarUsuarioResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorAccesoWS/consultarUsuarioRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorAccesoWS/consultarUsuarioResponse")
    public RespuestaDTO consultarUsuario(@WebParam(name = "usuarioAcceso", targetNamespace = "")
                                         ConsultarUsuarioDTO usuarioAcceso);

    /**
     *
     * @param usuarioAcceso
     * @return
     *     returns mx.frisa.tic.negocio.ws.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "agregarUsuario", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                    className = "mx.frisa.tic.negocio.ws.AgregarUsuario")
    @ResponseWrapper(localName = "agregarUsuarioResponse", targetNamespace = "http://ws.negocio.tic.frisa.mx/",
                     className = "mx.frisa.tic.negocio.ws.AgregarUsuarioResponse")
    @Action(input = "http://ws.negocio.tic.frisa.mx/GestorAccesoWS/agregarUsuarioRequest",
            output = "http://ws.negocio.tic.frisa.mx/GestorAccesoWS/agregarUsuarioResponse")
    public RespuestaDTO agregarUsuario(@WebParam(name = "usuarioAcceso", targetNamespace = "")
                                       AgregarUsuarioDTO usuarioAcceso);

}
