package mx.frisa.tic.negocio.ws;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class GestorPagosWSPortClient {
    public static void main(String[] args) {
        GestorPagosWS_Service gestorPagosWS_Service = new GestorPagosWS_Service();
        GestorPagosWS gestorPagosWS = gestorPagosWS_Service.getGestorPagosWSPort();
        FiltroPagoSinReferencia filtros= new FiltroPagoSinReferencia();
        
        RespuestaPagoSinReferencia respuestaPagos = gestorPagosWS.consultarPagosSinReferencia(filtros);
        for(LineaEstadoCuentaDTO linea: respuestaPagos.getLineas()){
            System.out.println(linea.conceptoMovimiento);
            }
        // Add your code to call the desired methods.


    }
}
